import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/rpcapi/sidebar';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: "category",
      label: "Nutzerguide",
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guides'
        },
      ]
    },
    {
      type: 'category',
      label: 'Integration Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations'
        }
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: apiSidebar,
    },
    {
      type: "category",
      label: "Geräte",
      items: [
        {
          type: 'autogenerated',
          dirName: 'devices'
        },
      ]
    },
  ],
};

export default sidebars;