name: Deploy documentation
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "docs/static/api/openapi.yaml"
            - "docs/**"
            - ".github/workflows/deploy_documentation.yml"

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: |
                  cd docs
                  npm ci

            - name: Get all changed files
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                files: docs/static/api/openapi.yaml

            - name: Generate API docs if openapi.yaml changed
              if: steps.changed-files.outputs.any_changed == 'true'
              working-directory: ./docs
              run: |
                  echo "openapi.yaml has changed, regenerating API docs..."
                  rm -rf docs/rpcapi
                  npx docusaurus gen-api-docs all

            - name: Build documentation
              run: |
                  cd docs
                  npm run build

            - name: Delete all current files
              run: aws s3 rm s3://docs.zaehlerfreunde.tld --recursive

            - name: Upload new files
              run: aws s3 cp docs/build s3://docs.zaehlerfreunde.tld --recursive

            - name: Invalidate distribution
              run: aws cloudfront create-invalidation --distribution-id E3M3YQNXRFL21A --paths "/*"

